#!/usr/bin/env bash

docker run --name pg-docker -d --rm -p 0.0.0.0:5432:5432 --network=proxylocal_docker-proxy-net -v $HOME/docker/volumes/postgres:/var/lib/postgresql/data -e POSTGRES_PASSWORD=docker postgres
